name = "gordon-tartan"
compatibility_date = "2026-02-22"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js"

[assets]
directory = "dist/"

[[d1_databases]]
binding = "DB"
database_name = "gordon-tartan-db"
database_id = "e0e62aa5-5586-4370-b7d9-e960a8a31437"
